pub mod backlinks;
pub mod create;
pub mod graph;
pub mod index;
pub mod init;
pub mod list;
pub mod query;
pub mod tags;
pub mod update;
pub mod watch;

pub use self::backlinks::get_backlinks;
pub use self::create::create_note;
pub use self::graph::{graph_neighbors, graph_orphans, graph_path, graph_stats};
pub use self::index::index_vault;
pub use self::init::init_vault;
pub use self::list::list_notes;
pub use self::query::query_notes;
pub use self::tags::list_tags;
pub use self::update::update_note;
pub use self::watch::watch_vault;
